### ISSUE TITLE
Crash when unlocking PC

### ISSUE THREAD

**Issue by arakan94** [spin83/multi-monitors-add-on#54] opened 2017-07-10 10:57 UTC
I use up to date Fedora 25 (GNOME 3.22.2 @ X11) and sometimes this Add-On crashes (and takes most extensions with it) when I lock PC and later unlock it.. It's also impossible to turn it on again until gnome-shell is restarted.

Here is log:
> čec 10 11:52:54 david-pc org.gnome.Shell.desktop[1696]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x1e00007 (GNOME Shel)
> čec 10 11:54:08 david-pc gnome-shell[1696]: gsignal.c:2641: instance '0x555bf32457d0' has no handler with id '1'
> čec 10 12:12:33 david-pc gnome-shell[1696]: JS LOG: pushModal: invocation of begin_modal failed
> čec 10 12:12:43 david-pc gnome-shell[1696]: gsignal.c:2641: instance '0x555bf0c490b0' has no handler with id '12502'
> čec 10 12:12:43 david-pc gnome-shell[1696]: JS LOG: remove: i1x0y0w1920h1080
> čec 10 12:12:43 david-pc gnome-shell[1696]: JS LOG: Disable Multi Monitors Add-On ...
> čec 10 12:12:43 david-pc gnome-shell[1696]: Allocating size to ShellEmbeddedWindow 0x555bf0be0b70 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
> čec 10 12:43:25 david-pc gnome-shell[1696]: JS LOG: Enable Multi Monitors Add-On ...
> čec 10 12:43:25 david-pc gnome-shell[1696]: JS LOG: pi:0
> čec 10 12:43:25 david-pc gnome-shell[1696]: JS LOG: i:0 x:1920 y:0 w:1920 h:1080
> čec 10 12:43:25 david-pc gnome-shell[1696]: JS LOG: i:1 x:0 y:0 w:1920 h:1080
> čec 10 12:43:25 david-pc gnome-shell[1696]: JS LOG: new: i1x0y0w1920h1080
> čec 10 12:43:25 david-pc gnome-shell[1696]: JS LOG: loading default theme (Adwaita)
> čec 10 12:43:25 david-pc gnome-shell[1696]: gsignal.c:2641: instance '0x555bf0c490b0' has no handler with id '12502'
> čec 10 12:43:25 david-pc gnome-shell[1696]: JS LOG: remove: i1x0y0w1920h1080
> čec 10 12:43:25 david-pc gnome-shell[1696]: JS LOG: Disable Multi Monitors Add-On ...
> čec 10 12:43:25 david-pc gnome-shell[1696]: JS LOG: loading default theme (Adwaita)
> čec 10 12:43:26 david-pc gnome-shell[1696]: JS LOG: loading default theme (Adwaita)
> čec 10 12:43:26 david-pc gnome-shell[1696]: gsignal.c:2641: instance '0x555bf0c490b0' has no handler with id '12502'

Last error repeats several times and then other extensions start to fail. Is there some another, more detailed log? Or perhaps a debug mode in your extension..? Can I provide any more info?

**Comment by n-goncharuk** [comment] 2017-07-12 13:58
I have crash on unlock on Fedora 26 if shell was locked when Activities overview had been opened.
It doesn't happens without the extension enabled.

**Comment by DChrome** [comment] 2017-08-04 09:00
I've had this add-on for more than a year. Locking-unlocking the computer almost every time crashed gnome-shell and most of the other extensions. Alt+F2, r solved the issue most of the time, though sometimes I had to restart the gnome-shell a couple of times in the row to get all my extensions back. Recently for some reason gnome-shell started to crash more severely, I was loosing all my open applications. I disabled the add-on and the crashes stopped. I really miss its functionality and it's a shame I can't use it anymore.

**Comment by bartmanus** [comment] 2017-08-24 09:59
This is most likely a duplicate of issue #49.

**Comment by n-goncharuk** [comment] 2017-09-02 16:52
I have upgraded the extansion to version 12 and I still have Crashes when I unlock session if it was locked when activities overview opened.

It is 100% reproducible for me when I use two monitors (I didn't tried more):

1. Enable "thumbnails slider on additional monitors" (I have only this enabled in extensions settings); n
2. Open activities overview.
3. Lock Shell (using hotkey or do nothing until it will lock automatically)
4. Enter your password and press Enter or "Unlock"

Expected result:
Shell shows Activities overview after unlock. (It is a behaviour without additional thumbnail slider or with only one monitor)

Actual result:
Shell Crashes instead of Unlock
(though I would end up unlocked after crash if xorg is used It takes more time and shows Crash report; but I use Wayland so I only get GDM login screen and Crash report after re-login)

Software version:
Fedora 26 x86_64
GNOME Shell 3.24.3
multi-monitors-add-on version 12

**Closed** 2017-10-11 18:52 UTC
