### ISSUE TITLE
Installing this extension breaks the right click menus

### ISSUE THREAD

**Issue by kamyarkaviani** [spin83/multi-monitors-add-on#94] opened 2019-06-17 22:58 UTC
I'm on Ubuntu 19.04 running Gnome 3.32.1 on X11 with GDM3 display manager. I have a laptop with an HDMI port to which I connect an external display, and I've selected that external display to be primary. Now, when I set the position of displays like so:

![oFbqnBm](https://user-images.githubusercontent.com/3037705/59641979-2bb47480-9118-11e9-916a-be8bad8da22d.png)

The right click menus on my external display appear at some weird offset from where it is supposed to be:

![BfxUZVU](https://user-images.githubusercontent.com/3037705/59642031-556d9b80-9118-11e9-9d6d-8cbc3cf2c7c3.png)

But when I set the display arrangement like so:

![yN6VzSI](https://user-images.githubusercontent.com/3037705/59642049-68806b80-9118-11e9-9c48-e74650c1be02.png)

It works as it should. It appears that the offset by which the right click context menu is away from the mouse is the distance between the top of the laptop monitor and mouse's y-position. This picture should summarize the problem:

![uaM1KOM](https://user-images.githubusercontent.com/3037705/59642095-92d22900-9118-11e9-91ca-430355e57a21.png)

Let me know if you anyone else can reproduce this issue, and if there is any additional information I should add here.

**Comment by vpant** [comment] 2019-08-14 14:40
This is also happens to be on Debian 10 with Gnome  3.30. Eclipse's menus also affected.

**Comment by spin83** [comment] 2019-09-29 14:42
This issue is a duplicate of #48

**Comment by AnzoDK** [comment] 2020-04-29 13:02
Same issue is there on Pop!_OS 19.10

**Comment by spin83** [comment] 2020-11-15 12:36
Fixed upstream in gnome-shell.

**Closed by spin83** 2020-11-15 12:36 UTC
