### ISSUE TITLE
AppMenu-Button doesn't show selected app on second monitor

### ISSUE THREAD

**Issue by krisgospc** [spin83/multi-monitors-add-on#51] opened 2017-06-09 17:29 UTC
When the AppMenu-Button is on on the second monitor, it only shows what is selected on the first. I have recorded a Loom video of the issue here: https://www.useloom.com/share/0963ef6cf90a4e4292cac35f737b188e

**Comment by alex-kowalczyk** [comment] 2017-06-29 08:05
Confirming the issue, have the same.

**Comment by sebastiaanfranken** [comment] 2017-07-14 21:38
I also have this issue.

**Comment by rick-pri** [comment] 2017-10-20 08:21
I have the foreground app on two out of three monitors, so I have the same/similar issue.

**Comment by spin83** [comment] 2017-11-30 23:21
This is a duplicate of issue #46 .

**Closed** 2018-02-28 19:16 UTC
