### ISSUE TITLE
Overview is cluttered with Multi monitors add-on

### ISSUE THREAD

**Issue by BuZZ-dEE** [spin83/multi-monitors-add-on#131] opened 2020-08-03 10:55 UTC
Please see [gnome-shell/-/issues/3036](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/3036). Especially that [comment](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/3036#note_881764).

**Comment by fcastilloec** [comment] 2020-08-12 23:58
This is a duplicate of #125 and there's a fix 302c28b

**Closed** 2020-08-13 06:27 UTC
