### ISSUE TITLE
Behaves erratically on GnomeShell 1:3.32.0-1 on Arch

### ISSUE THREAD

**Issue by Zappo-II** [spin83/multi-monitors-add-on#85] opened 2019-03-18 11:42 UTC
After upgrade of GnomeShell to 3.32 on ArchLinux extension behaves erratically...
* No icon is shown (but menu is present)...
* None of the setings is working any more (nothing shows up on second display)...
* `journalctl /usr/bin/gnome-shell` states errors...

```
Mär 18 12:14:35 weareborg gnome-shell[1380]: Enable Multi Monitors Add-On (v17)...
Mär 18 12:14:35 weareborg gnome-shell[1380]: Add Monitors ...
Mär 18 12:14:35 weareborg gnome-shell[1380]: JS WARNING: [/home/arch-un/.local/share/gnome-shell/extensions/multi-monitors-add-on@spin83/mmpanel.js 386]: reference to undefined property "GenericContainer"
Mär 18 12:14:35 weareborg gnome-shell[1380]: Extension "multi-monitors-add-on@spin83" had error: TypeError: Shell.GenericContainer is not a constructor
```
Environment Info:
- Using
    - Arch Linux
    - X.Org X Server 1.20.4
    - GNOME Shell 3.32.0

```
[arch-un@weareborg ~]$ uname -a
Linux weareborg 5.0.2-arch1-1-ARCH #1 SMP PREEMPT Thu Mar 14 18:47:49 UTC 2019 x86_64 GNU/Linux
[arch-un@weareborg ~]$ gnome-shell --version
GNOME Shell 3.32.0
[arch-un@weareborg ~]$ sudo X -version

X.Org X Server 1.20.4
X Protocol Version 11, Revision 0
Build Operating System: Linux Arch Linux
Current Operating System: Linux weareborg 5.0.2-arch1-1-ARCH #1 SMP PREEMPT Thu Mar 14 18:47:49 UTC 2019 x86_64
Kernel command line: BOOT_IMAGE=/vmlinuz-linux root=/dev/mapper/main-root rw cryptdevice=/dev/disk/by-uuid/ac2b461d-c9c8-4096-9d29-58aaf6678fa7:lvm root=/dev/mapper/main-root
Build Date: 27 February 2019  04:04:00PM
 
Current version of pixman: 0.38.0
	Before reporting problems, check http://wiki.x.org
	to make sure that you have the latest version.
[arch-un@weareborg ~]$
```
---
Edit: Typo fixed...
Edit²: Added Environment Info...
Edit³: Added even more Environment Info...

**Comment by jacobmischka** [comment] 2019-03-18 13:42
Additionally, the extension crashes the gnome desktop session on Wayland on Arch with 3.32.

**Comment by saedabdu** [comment] 2019-03-18 14:12
I have been keeping gnome-shell locked on v3.30 through pacman for the sack of the compatibility of this plugin, until yesterday I wasn't able to login due to some compatibility issues with the newer gnome-shell related pkgs that forced me to upgrade to gnome-shell32. I had to remove the plugins altogether as it started to misbehave after losing all functionality. I really need this plugin.

**Comment by edrose** [comment] 2019-03-19 14:27
I can add to this. The extension was causing a complete segfault in gnome-shell whenever I tried to show the activities overview. On Wayland the entire session dies with gnome-shell. On XOrg most of the time just the shell crashes and restarts, but occasionally the entire X-Session would also die.

The extension appeared in an error state and therefore couldn't be disabled. It had to be completely uninstalled to fix the crashing. 

Error messages during the crash:

```
Mar 18 13:33:49 ed-laptop gnome-shell[2575]: JS ERROR: TypeError: this.actor is null
                                             _updateWorkspacesActualGeometry@resource:///org/gnome/shell/ui/workspacesView.js:647:13
                                             _updateWorkspacesViews@resource:///org/gnome/shell/ui/workspacesView.js:566:9
                                             show@resource:///org/gnome/shell/ui/workspacesView.js:482:9
                                             show@resource:///org/gnome/shell/ui/viewSelector.js:268:9
                                             _animateVisible@resource:///org/gnome/shell/ui/overview.js:527:9
                                             show@resource:///org/gnome/shell/ui/overview.js:513:9
                                             toggle@resource:///org/gnome/shell/ui/overview.js:636:13
                                             _initializeUI/<@resource:///org/gnome/shell/ui/main.js:190:13
Mar 18 13:33:49 ed-laptop gnome-shell[2575]: clutter_paint_volume_set_width: assertion 'width >= 0.0f' failed
Mar 18 13:33:49 ed-laptop gnome-shell[2575]: clutter_paint_volume_set_width: assertion 'width >= 0.0f' failed
Mar 18 13:33:49 ed-laptop gnome-shell[2575]: st_theme_node_render_resources: assertion 'width > 0 && height > 0' failed
Mar 18 13:33:49 ed-laptop audit[2575]: ANOM_ABEND auid=1000 uid=1000 gid=1000 ses=7 pid=2575 comm="gnome-shell" exe="/usr/bin/gnome-shell" sig=11 res=1
Mar 18 13:33:49 ed-laptop gnome-shell[2575]: st_theme_node_get_border_color: assertion 'ST_IS_THEME_NODE (node)' failed
Mar 18 13:33:49 ed-laptop gnome-shell[2575]: st_theme_node_get_border_width: assertion 'ST_IS_THEME_NODE (node)' failed
Mar 18 13:33:49 ed-laptop gnome-shell[2575]: st_theme_node_get_border_width: assertion 'ST_IS_THEME_NODE (node)' failed
Mar 18 13:33:49 ed-laptop gnome-shell[2575]: st_theme_node_get_border_width: assertion 'ST_IS_THEME_NODE (node)' failed
Mar 18 13:33:49 ed-laptop gnome-shell[2575]: st_theme_node_get_border_width: assertion 'ST_IS_THEME_NODE (node)' failed
Mar 18 13:33:49 ed-laptop kernel: gnome-shell[2575]: segfault at 80 ip 00007f2666e52180 sp 00007ffd94a6b618 error 4 in libst-1.0.so[7f2666e52000+2d000]
Mar 18 13:33:49 ed-laptop kernel: Code: 7f 18 8b 77 7c 85 f6 7f 11 8b 4f 74 85 c9 7f 0a 8b 57 78 31 c0 85 d2 0f 9f c0 c3 66 66 2e 0f 1f 84 00 00 00 00 00 0f 1f 40 00 <8b> 87 80 00 00 00 8b 97 84 00 00 00 f3 0f 10 15 b0 ec 02 00 89 c1
Mar 18 13:33:49 ed-laptop kernel: audit: type=1701 audit(1552916029.196:162): auid=1000 uid=1000 gid=1000 ses=7 pid=2575 comm="gnome-shell" exe="/usr/bin/gnome-shell" sig=11 res=1
Mar 18 13:33:49 ed-laptop systemd[1]: Started Process Core Dump (PID 2993/UID 0).
Mar 18 13:33:49 ed-laptop audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@1-2993-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Mar 18 13:33:49 ed-laptop kernel: audit: type=1130 audit(1552916029.216:163): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@1-2993-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
```
I also have the Gnome Shell backtrace and core dump if it's useful.

**Comment by mallardduck** [comment] 2019-03-19 21:41
I haven't looked over the others enough to confirm/deny, but I can say for sure that @Zappo-II is reporting an issue related to Gnome's [pretty big change removing deprecated methods](https://gitlab.gnome.org/GNOME/gnome-shell/merge_requests/153).

**Comment by mallardduck** [comment] 2019-03-19 21:54
@edrose & @jacobmischka: it's interesting that you two experience a crash - do either of you see any traces of the error in the OP? Your issue could be distinct from this one.

I'm not on Wayland and experiencing the exact issue as the OP

```
Mar 19 17:03:36 seymournx gnome-shell[1905]: Enable Multi Monitors Add-On (v17)...
Mar 19 17:03:36 seymournx gnome-shell[1905]: Add Monitors ...
Mar 19 17:03:36 seymournx gnome-shell[1905]: JS WARNING: [/home/dan/.local/share/gnome-shell/extensions/multi-monitors-add-on@spin83/mmpanel.js 386]: reference to undefined property "GenericContainer"
Mar 19 17:03:36 seymournx gnome-shell[1905]: Extension "multi-monitors-add-on@spin83" had error: TypeError: Shell.GenericContainer is not a constructor
```

If you're not seeing the same in the logs then it may be worth reporting as a seperate issue.

**Comment by edrose** [comment] 2019-03-20 09:50
@mallardduck & @jacobmischka: just searched through my logs, I have lots of the same log messages too. You may be right that this is a distinct issue however, since it doesn't seem to immediately precede a crash.

I've opened #86 describing my specific issue in detail.

**Comment by Zappo-II** [comment] 2019-03-20 12:43
Some Maintainer Motivation... :heart_decoration: :heart: :heart_decoration: ...
* Really like and appreciate this plugin...
* Am really sad it's not working with Gnome-Shell 3.32 right now...
* Craving for a fix on this issue...
* Greatly appreciate all the time and work you spent on this functionality...
* Looking forward to be able to use this one again...

**Comment by mallardduck** [comment] 2019-03-20 13:24
Also, I just noticed it looks like this issue is a duplicate of #83.

**Comment by spin83** [comment] 2019-03-20 18:28
So, some „cosmetic changes” in gnome-shell 3.32 completely brake this extension.
I made initial work in branch [wip_gnome_3_32](https://github.com/spin83/multi-monitors-add-on/tree/wip_gnome_3_32) to fix this issues, but it’s not ready yet.

**Closed** 2019-04-27 13:31 UTC
