### ISSUE TITLE
 Gnome overview break

### ISSUE THREAD

**Issue by ruifernandees** [spin83/multi-monitors-add-on#127] opened 2020-07-30 19:22 UTC
I was using the extension normally and after a system update (my system is Pop!_OS 20.04 LTS) the extension broke the Gnome overview.

With the extension:
(
![Screenshot from 2020-07-30 16-15-22](https://user-images.githubusercontent.com/23262436/88964834-50b66900-d280-11ea-8daf-e352db6dc43f.png)
)

Without the extension (after disable and Gnome reloading):
![Screenshot from 2020-07-30 16-20-57](https://user-images.githubusercontent.com/23262436/88965141-b4d92d00-d280-11ea-9205-6f0ed307eac9.png)

**Comment by austinkeller** [comment] 2020-07-30 19:30
This is a duplicate of #125

**Comment by ruifernandees** [comment] 2020-08-03 14:53
Installing from GitHub repository fixed the error

**Closed** 2020-08-03 14:53 UTC
