### ISSUE TITLE
Dialog opens at weird place

### ISSUE THREAD

**Issue by yfiua** [spin83/multi-monitors-add-on#61] opened 2017-12-05 09:54 UTC
All gnome notifications (e.g., facebook) and system dialogs, including screenshot and the preference of this add-on, open at weird place if in ``Display'', monitors are arranged not exactly horizontally, and ``show panels on additional monitors'' is chosen at.

**Comment by spin83** [comment] 2018-09-29 19:05
This issue is a duplicate of #48

**Comment by spin83** [comment] 2020-11-15 12:38
Fixed upstream in gnome-shell.

**Closed by spin83** 2020-11-15 12:38 UTC
