### ISSUE TITLE
pixel-saver and muti-monitors-add-on error when locking

### ISSUE THREAD

**Issue by clausavram** [spin83/multi-monitors-add-on#84] opened 2019-03-14 09:28 UTC
I've enabled both **pixel-saver** and **multi-monitors-add-on** and when locking gnome (Super+L), the lock screen does not appear, but the screen becomes completely purple. I have to hit Super+L again to see the lock screen and login dialog. After unlocking, gnome's appearance is altered, as if soft-crashing:
- Ubuntu Gnome UI reverts to stock Gnome style
- extensions are disabled (and some others can't be re-enabled due to exceptions from these 2) and can't be re-enabled until the next log-out + re-login

The issue reproduces for me only if both extensions are enabled at the same time.

I've captured a _gnome-shell_ log (`journalctl  /usr/bin/gnome-shell -f`) with exceptions of the error-ed locking:
- 10:47:18 - enable multi-monitors-add-on, then pixel-saver
- 10:47:47 - log out + re-login - otherwise the issue does not reproduce
- 10:49:03 - 1st lock (Super+L) - screen becomes purple
- 10:49:36 - 2nd lock (Super+L) - lock screen appears and I can enter my password to unlock
- 10:50:22 - unlock -> all extensions have been disabled, with some not allowed to re-enable, Gnome UI appearance changed
- 10:50:28 - 3rd lock (Super+L) - confirmed that the issue still occurs -> last logging is the exception again

```
$ apt list | grep -e pixelsaver -e multi-monitors
gnome-shell-extension-multi-monitors/bionic,bionic 0.00~git20171014.1.df5d6e4-1 all
gnome-shell-extension-pixelsaver/bionic,bionic 1.10+git20161217-49f47bf-1 all


$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic

$ uname -a
Linux ubuntu-machine 4.15.0-46-generic #49-Ubuntu SMP Wed Feb 6 09:33:07 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

pixel-saver issue: https://github.com/deadalnix/pixel-saver/issues/194

[gnome-shell.log.tar.gz](https://github.com/spin83/multi-monitors-add-on/files/2965644/gnome-shell.log.tar.gz)

**Comment by spin83** [comment] 2019-09-29 14:52
This issue is a duplicate of #79
Generally this two extension are not compatible.

**Closed** 2020-05-03 16:12 UTC
