### ISSUE TITLE
Application menu tied to focused application on main display

### ISSUE THREAD

**Issue by jpaniagualaconich** [spin83/multi-monitors-add-on#46] opened 2017-04-06 12:11 UTC
1. Open Apps A, B on main display
2. Move App B to secondary
3. Focus on App B
4. Application menu (in both displays) shows App A (or whatever is focused) on the main display.

Ubuntu 17.04, gnome shell 3.24.0, version 11 of this add-on

**Comment by BenJetson** [comment] 2017-04-13 16:29
Same issue on Ubuntu GNOME 17.04 with GNOME Shell v3.24, and extension v11.

**Comment by PioneerAxon** [comment] 2017-04-19 17:02
I have the same issue on Archlinux, GNOME Shell 3.24.1, extension is up to date from gnome extensions site.

It used to work with GNOME Shell 3.22.3. Has to be something that changed in 3.24 series.

**Comment by rick-pri** [comment] 2017-10-24 14:01
Issue [#50](https://github.com/spin83/multi-monitors-add-on/issues/50) is a duplicate of this.

**Closed** 2018-02-28 19:13 UTC
